### ISSUE TITLE
Focusing with animated camers!?

### ISSUE THREAD

**Issue by nurb2kea** [hrkck/Autofocus_Modern#1]
Hi,

just came across the autofocus addon and tried it.
Works fine except when you animate the camera to see different meshes.

I simply animated the x axis of the camera x rotation so I could look from top to bottom in the scene. There are several meshes at different distances. Then the autofocus isn't updated...
Is that the timer that isn't working yet, to update the focus?

Thanks in advance

SG

**Comment by hrkck** [comment]
Hi,

Thanks for the report. The update function was running everytime dependency graph was updating, to that, I added a hook for every time the frame changes. 

Let me know if it works with the latest commit. 

Both the timer and the smooth function does not work right now. The original script had them implemented using an internal Blender feature called "slow parent", which does not exist in newer versions of Blender anymore :/ ... So we need to find an optimum way to implement them at some point.

**Comment by nurb2kea** [comment]
Thanks for updating it. Works perfect now.
Wohoo 👍
